[package]
name = "magnify"
version = "0.1.0"
edition = "2021"
license = "EUPL-1.2"
keywords = ["pixel-art", "graphics"]
categories = ["multimedia::images"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.6"
